package com.app.fdaccount.entity;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity representing periodic account statements for FD accounts
 * Generated by batch jobs to summarize account activity and balances
 */
@Entity
@Table(name = "account_statements")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AccountStatement {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "account_id", nullable = false)
    private FdAccount account;
    
    @Column(name = "statement_reference", unique = true, nullable = false)
    private String statementReference;
    
    @Enumerated(EnumType.STRING)
    @Column(name = "statement_type", nullable = false)
    private StatementType statementType;
    
    @Column(name = "statement_date", nullable = false)
    private LocalDate statementDate;
    
    @Column(name = "period_start_date", nullable = false)
    private LocalDate periodStartDate;
    
    @Column(name = "period_end_date", nullable = false)
    private LocalDate periodEndDate;
    
    @Column(name = "opening_principal_balance", precision = 15, scale = 2)
    private BigDecimal openingPrincipalBalance;
    
    @Column(name = "closing_principal_balance", precision = 15, scale = 2)
    private BigDecimal closingPrincipalBalance;
    
    @Column(name = "opening_interest_balance", precision = 15, scale = 2)
    private BigDecimal openingInterestBalance;
    
    @Column(name = "closing_interest_balance", precision = 15, scale = 2)
    private BigDecimal closingInterestBalance;
    
    @Column(name = "interest_accrued", precision = 15, scale = 2)
    private BigDecimal interestAccrued;
    
    @Column(name = "interest_paid", precision = 15, scale = 2)
    private BigDecimal interestPaid;
    
    @Column(name = "total_credits", precision = 15, scale = 2)
    private BigDecimal totalCredits;
    
    @Column(name = "total_debits", precision = 15, scale = 2)
    private BigDecimal totalDebits;
    
    @Column(name = "transaction_count")
    private Integer transactionCount;
    
    @Column(name = "total_closing_balance", precision = 15, scale = 2)
    private BigDecimal totalClosingBalance;
    
    @Column(name = "summary", columnDefinition = "TEXT")
    private String summary;
    
    @Column(name = "generated_by")
    private String generatedBy;
    
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
    
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }
    
    /**
     * Statement type enum
     */
    public enum StatementType {
        DAILY,
        WEEKLY,
        MONTHLY,
        QUARTERLY,
        ANNUAL,
        ON_DEMAND
    }
}
